server:
  port: 8761
eureka:
  instance:
    hostname: 112.74.161.0
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
